version = 0.1

[default.global.parameters]
stack_name = "gamelab-share"

[default.deploy.parameters]
profile = "ohstem"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "gamelab-share"
parameter_overrides = "Stage=prod RetentionDays=0"
